mysite/myauth/urls.py
from django.urls import path

from .views import (
    get_cookie_view,
    set_cookie_view,
    set_session_view,
    get_session_view,
    MyLogoutView,
    MyLoginView,
    AboutMeView,
    RegisterView,
    MyProfileUpdateView,
    ProfilesListView,
    HelloView,
)


app_name = "myauth"

urlpatterns = [
    path("hello/", HelloView.as_view(), name="hello"),
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", MyLoginView.as_view(), name="login"),
    path("logout/", MyLogoutView.as_view(), name="logout"),
    path("", ProfilesListView.as_view(), name="profiles_list"),
    path("about-me/<int:pk>/", AboutMeView.as_view(), name="about-me"),
    path("about-me/<int:pk>/update/", MyProfileUpdateView.as_view(), name="profile_update"),
    path("cookie/get", get_cookie_view, name="cookie-get"),
    path("cookie/set", set_cookie_view, name="cookie-set"),
    path("session/get", get_session_view, name="session-get"),
    path("session/set", set_session_view, name="session-set"),
]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from .sitemaps import sitemaps
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView



urlpatterns = [
    path('req/', include('requestdataapp.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name="schema"),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name="swagger"),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name="redoc"),
    path('api/', include('myapiapp.urls')),
    path('blog/', include('blogapp.urls')),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]

urlpatterns += i18n_patterns(
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('myauth.urls')),
    path('shop/', include('shopapp.urls')),
)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

mysite/shopapp/urls.py
from rest_framework.routers import DefaultRouter
from django.urls import path, include
from django.views.decorators.cache import cache_page
from .views import (
    ShopIndexView,
    ProductsListView,
    ProductDetailsView,
    OrdersListView,
    OrderDetailView,
    OrderCreateView,
    OrderDeleteView,
    OrderUpdateView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    OrderDataExportView,
    ProductDataExportView,
    ProductViewSet,
    OrderViewSet,
    LatestProductsFeed,
    UserOrdersListView,
    OrderCacheExportView,
)

app_name = "shopapp"

routers = DefaultRouter()
routers.register("products", ProductViewSet)
routers.register("orders", OrderViewSet)

urlpatterns = [
    path("", cache_page(60 * 3)(ShopIndexView.as_view()), name="shop_index"),
    # path("", ShopIndexView.as_view(), name="shop_index"),
    path("api/", include(routers.urls)),
    path("products/", ProductsListView.as_view(), name="products_list"),
    path("products/create/", ProductCreateView.as_view(), name="product_create"),
    path("products/<int:pk>/", ProductDetailsView.as_view(), name="product_details"),
    path("products/<int:pk>/update/", ProductUpdateView.as_view(), name="product_update"),
    path("products/<int:pk>/archive/", ProductDeleteView.as_view(), name="product_delete"),
    path("products/export", ProductDataExportView.as_view(), name="products-export"),
    path("products/latest/feed/", LatestProductsFeed(), name="products-feed"),
    path("orders/<int:pk>/", OrderDetailView.as_view(), name="order_details"),
    path("orders/", OrdersListView.as_view(), name="orders_list"),
    path("orders/export", OrderDataExportView.as_view(), name="orders-export"),
    path("orders/create/", OrderCreateView.as_view(), name="order_create"),
    path("orders/<int:pk>/confirm-delete/", OrderDeleteView.as_view(), name="order_delete"),
    path("orders/<int:pk>/confirm-update/", OrderUpdateView.as_view(), name="order_update"),
    path("users/<int:user_id>/orders/", UserOrdersListView.as_view(), name="user_orders"),
    path("users/<int:user_id>/orders/export", OrderCacheExportView.as_view(), name="orders-export-cached"),
]

mysite/shopapp/forms.py
from django import forms
from .models import Product, Order
from django.contrib.auth.models import Group


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "name", "price", "description", "discount", "preview",

    images = forms.ImageField(
        widget=forms.ClearableFileInput(attrs={"multiple": True}),
    )


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = "delivery_address", "promocode", "products", "user"


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['name']


class CSVImportForm(forms.Form):
    csv_file = forms.FileField()

mysite/shopapp/views.py
"""
В этом модуле лежат различные наборы представлений.

Разные view интернет-магазина: по товарам, заказам и т.д.
"""
import logging
from csv import DictWriter
from timeit import default_timer

from django.contrib.auth.models import User
from django.core.cache import cache
from django.contrib.syndication.views import Feed
from django.shortcuts import reverse, get_object_or_404
from django.http import (
    HttpResponse,
    HttpRequest,
    HttpResponseRedirect,
    JsonResponse
)
from django.shortcuts import render
from django.views.decorators.cache import cache_page

from .common import save_csv_products
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import (
    DetailView,
    ListView,
    CreateView,
    UpdateView,
    DeleteView
)
from .models import Product, Order, ProductImage
from .forms import ProductForm
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    PermissionRequiredMixin,
    UserPassesTestMixin
)
from rest_framework.viewsets import ModelViewSet
from rest_framework.decorators import action
from rest_framework.parsers import MultiPartParser
from rest_framework.request import Request
from rest_framework.response import Response
from rest_framework.filters import SearchFilter, OrderingFilter
from .serializers import ProductSerializer, OrderSerializer
from django_filters.rest_framework import DjangoFilterBackend
from drf_spectacular.utils import extend_schema, OpenApiResponse

log = logging.getLogger(__name__)


@extend_schema(description="Product views CRUD")
class ProductViewSet(ModelViewSet):
    """
    Набор представлений для действий над Product.

    Полный CRUD для сущностей товара.
    """

    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    filter_backends = [
        SearchFilter,
        DjangoFilterBackend,
        OrderingFilter,
    ]
    search_fields = ["name", "description"]
    filterset_fields = [
        "name",
        "description",
        "price",
        "discount",
        "archived",
    ]
    ordering_fields = [
        "name",
        "price",
        "discount",
    ]

    @method_decorator(cache_page(60 * 2))
    def list(self, *args, **kwargs):
        return super().list(*args, **kwargs)

    @extend_schema(
        summary="Get one product by ID",
        description="Retrieves **product**, returns 404 if not found ",
        responses={
            200: ProductSerializer,
            # 404: None,
            404: OpenApiResponse(description="Empty response, product by id not found"),
        }
    )
    def retrieve(self, *args, **kwargs):
        return super().retrieve(*args, **kwargs)

    @action(methods=["get"], detail=False)
    def download_csv(self, request: Request):
        response = HttpResponse(content_type="text/csv")
        filename = "products-export.csv"
        response["Content-Disposition"] = f"attachment; filename={filename}"
        queryset = self.filter_queryset(self.get_queryset())
        fields = [
            "name",
            "description",
            "price",
            "discount",
        ]
        queryset = queryset.only(*fields)
        writer = DictWriter(response, fieldnames=fields)
        writer.writeheader()

        for product in queryset:
            writer.writerow({
                field: getattr(product, field)
                for field in fields
            })
        return response

    @action(
        detail=False,
        methods=["post"],
        parser_classes=[MultiPartParser],
    )
    def upload_csv(self, request: Request):
        products = save_csv_products(
            request.FILES["file"].file,
            encoding=request.encoding,
        )
        serializer = self.get_serializer(products, many=True)
        return Response(serializer.data)


class OrderViewSet(ModelViewSet):
    queryset = Order.objects.all()
    serializer_class = OrderSerializer
    filter_backends = [
        DjangoFilterBackend,
        OrderingFilter,
    ]
    filterset_fields = [
        "delivery_address",
        "promocode",
        "created_at",
        "user",
        "products",
    ]
    ordering_fields = [
        "user",
        "created_at",
    ]


class ShopIndexView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        links = [
            {"title": "Список продуктов", "address": "products/"},
            {"title": "Список заказов", "address": "orders/"},
        ]
        context = {
            "time_running": default_timer(),
            "links": links,
            "items": 5,
        }
        log.debug("Products for shop index: %s", links)
        log.info("Rendering shop index")
        print("shop index context", context)
        return render(request, 'shopapp/shop-index.html', context=context)


class OrdersListView(LoginRequiredMixin, ListView):
    queryset = (
        Order.objects
        .select_related("user")
        .prefetch_related("products")
    )


class OrderDetailView(PermissionRequiredMixin, DetailView):
    permission_required = "shopapp.view_order"
    queryset = (
        Order.objects
        .select_related("user")
        .prefetch_related("products")
    )


class OrderCreateView(CreateView):
    model = Order
    fields = "user", "products", "promocode", "delivery_address"
    success_url = reverse_lazy("shopapp:orders_list")


class OrderDeleteView(DeleteView):
    model = Order
    success_url = reverse_lazy("shopapp:orders_list")


class OrderUpdateView(UpdateView):
    model = Order
    fields = "user", "products", "promocode", "delivery_address"
    template_name_suffix = "_update_form"

    def get_success_url(self):
        return reverse(
            "shopapp:order_details",
            kwargs={"pk": self.object.pk},
        )


class OrderDataExportView(View, UserPassesTestMixin):

    def test_func(self):
        return self.request.user.is_staff

    def get(self, request: HttpRequest) -> JsonResponse:
        orders = Order.objects.order_by("pk").all()
        orders_data = [
            {
                "pk": order.pk,
                "address": order.delivery_address,
                "promocode": order.promocode,
                "user": order.user.id,
                "products": [product.id for product in order.products.all()]
            }
            for order in orders
        ]
        return JsonResponse({"orders": orders_data})


class ProductDetailsView(DetailView):
    template_name = "shopapp/products-details.html"
    queryset = Product.objects.prefetch_related("images")
    context_object_name = "product"


class ProductsListView(ListView):
    template_name = 'shopapp/products-list.html'
    # model = Product
    context_object_name = "products"
    queryset = (
        Product.objects.filter(archived=False)
        .filter(created_at__isnull=False)
        .order_by("-created_at")
    )


class ProductCreateView(PermissionRequiredMixin, CreateView):
    permission_required = "shopapp.add_product"
    model = Product
    fields = "name", "price", "description", "discount"
    success_url = reverse_lazy("shopapp:products_list")

    def form_valid(self, form):
        form.instance.created_by_id = self.request.user.id
        return super().form_valid(form)


class ProductUpdateView(PermissionRequiredMixin, UserPassesTestMixin, UpdateView):

    permission_required = "shopapp.change_product"
    model = Product
    # fields = "name", "price", "description", "discount", "preview"
    form_class = ProductForm
    template_name_suffix = "_update_form"

    def test_func(self):
        return self.request.user.id == self.get_object().created_by_id or self.request.user.is_superuser

    def get_success_url(self):
        return reverse(
            "shopapp:product_details",
            kwargs={"pk": self.object.pk},
        )

    def form_valid(self, form):
        response = super().form_valid(form)
        for image in form.files.getlist("images"):
            ProductImage.objects.create(
                product=self.object,
                image=image,
            )
        return response


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy("shopapp:products_list")

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)


class ProductDataExportView(View, UserPassesTestMixin):

    def test_func(self):
        return self.request.user.is_staff

    def get(self, request: HttpRequest) -> JsonResponse:
        cache_key = "products_data_export"
        products_data = cache.get(cache_key)
        products = Product.objects.order_by("pk").all()
        if products_data is None:
            products_data = [
                {
                    "pk": product.pk,
                    "name": product.name,
                    "price": product.price,
                    "archived": product.archived,
                }
                for product in products
            ]
            cache.set(cache_key, products_data, 3000)
        return JsonResponse({"products": products_data})


class LatestProductsFeed(Feed):
    title = "Shop products (latest)"
    description = "Updates on changes and addition products"
    link = reverse_lazy("shopapp:products_list")

    def items(self):
        return (
            Product.objects
            .select_related("created_by")
            .prefetch_related("images")
            .filter(created_at__isnull=False)
            .order_by("-created_at")[:5]
        )

    def item_title(self, item: Product):
        return item.name

    def item_description(self, item: Product):
        return item.description[:200]


class UserOrdersListView(LoginRequiredMixin, ListView):
    template_name = "shopapp/user_orders.html"

    def get_queryset(self, owner=None, **kwargs):

mysite/shopapp/templates/shopapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Base Title
        {% endblock %}
    </title>
</head>
<body>
    {% block body %}
        Base body
    {% endblock %}

    {% now 'H:i' %}
    <div>
        {% now 'l' as current_weekday %}
        Today is {{current_weekday}}
    </div>

</body>
</html>

mysite/shopapp/templates/shopapp/create-order.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create order
{% endblock %}

{% block body %}
    <h1>Create a new order</h1>
    <div>
        <form method="post">
            {% csrf_token %}

            {{form.as_p}}

            <button type="submit">Create order</button>
        </form>
    </div>

    <div>
        <a href="{% url 'shopapp:orders_list' %}">
            Back to orders list
        </a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/create-product.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create product
{% endblock %}

{% block body %}
    <h1>Create a new product</h1>
    <div>
        <form method="post">
            {% csrf_token %}

            {{form.as_p}}

            <button type="submit">Create</button>
        </form>
    </div>

    <div>
        <a href="{% url 'shopapp:products_list' %}">
            Back to products list
        </a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/groups-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Groups list
{% endblock %}

{% block body %}
    <h1>Groups:</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
    <div>
    {% if not groups %}
        <h3>No groups yet</h3>
    {% else %}
        <ul>
            {% for group in groups %}
                <li>
                    <div>{{group.name}}</div>
                    <ul>
                        {% for permission in group.permissions.all %}
                            <li>
                                {{permission.name}}
                                (<code>{{permission.codename}}</code>)
                            </li>
                        {% endfor %}
                    </ul>
                </li>
            {% endfor %}
        </ul>
    {% endif %}
    </div>

    <div>
        <a href="{% url 'shopapp:shop_index' %}">
            Back to the shop
        </a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Confirm Archive {{ object.name }}
{% endblock %}

{% block body %}
    <h1>Are you sure you want to delete {{ object.name }}?</h1>
    <br>
    <div>
        <a href="{% url 'shopapp:order_details' pk=object.pk %}"
        >Back to order</a>
    </div>
    <br>
    <div>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Delete</button>
      </form>
    </div>

{% endblock %}

mysite/shopapp/templates/shopapp/order_list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Orders list
{% endblock %}

{% block body %}
    <h1>Orders:</h1>
    {% if object_list %}
        <div>
        {% for order in object_list %}
            <div>
                <p><a href="{% url 'shopapp:order_details' pk=order.pk %}">
                    Details # {{ order.pk }}</a></p>
                <p>Order by: {% firstof order.user.first_name order.user.username %}</p>
                <p>Promocode: <code>{{ order.promocode }}</code></p>
                <p>Delivery address: {{ order.delivery_address }}</p>
            </div>
                Products in order:
                <ul>
                    {% for product in order.products.all %}
                        <li>{{ product.name }} for ${{product.price}}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endfor %}
        </div>
    {% else %}
        <h3>No orders yet</h3>
    {% endif %}

    <div>
        <a href="{% url 'shopapp:order_create' %}">
            Create a new order
        </a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_update_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Update product
{% endblock %}

{% block body %}
    <h1>Update order:</h1>
    <div>Update
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update</button>
        </form>
    </div>
    <div>
        <a href="{% url 'shopapp:order_details' pk=object.pk %}"
        >Back to orders #{{ object.pk }}</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Confirm Archive {{ object.name }}
{% endblock %}

{% block body %}
    <h1>Are you sure you want to Archive {{ object.name }}?</h1>
    <br>
    <div>
        <a href="{% url 'shopapp:product_details' pk=object.pk %}"
        >Back to products</a>
    </div>
    <br>
    <div>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Archive</button>
      </form>
    </div>

{% endblock %}

mysite/shopapp/templates/shopapp/product_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create product
{% endblock %}

{% block body %}
    <h1>Create product:</h1>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
    <div>
        <a href="{% url 'shopapp:products_list' %}"
        >Back to products list</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/products-details.html
{% extends 'shopapp/base.html' %}

{% load i18n %}

{% block title %}
    {% translate 'Product' %} #{{product.pk}}
{% endblock %}

{% block body %}
<h1>{% translate 'Product' %} <strong>{{ product.name }}</strong></h1>
<div>
    <div>{% translate 'Description' %}: <em>{{ product.description }}</em></div>
    <div>{% translate 'Price' %}: {{ product.price }}</div>
    <div>{% translate 'Discount' %}: {{ product.discount }}</div>
    <div>{% translate 'Archived' context 'Product status' %}: {{ product.archived }}</div>
    {% if product.preview %}
        <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
    {% endif %}
    <h3>{% translate 'Images' %}</h3>
    <div>
        {% if product.images.all|length != 0 %}
            {% blocktranslate count images_count=product.images.all|length %}
            There is only one image
            {% plural %}
            There are {{ images_count }} images
            {% endblocktranslate %}
        {% endif %}
    </div>
    <div>
        {% for img in product.images.all %}
            <div>
                <img src="{{img.image.url}}" alt="{{img.image.name}}">
                <div>{{ img.description }}</div>
            </div>
        {% empty %}
            <div>{% translate 'No images uploaded yet' %}</div>
        {% endfor %}
    </div>
</div>
<p>{% translate 'Created by' %}: {% firstof object.created_by.first_name object.created_by.username %}</p>
<div>
    <a href="{% url 'shopapp:product_update' pk=product.pk %}">{% translate 'Update product' %}</a>
</div>
<div>
    <a href="{% url 'shopapp:product_delete' pk=product.pk %}">{% translate 'Archive product' %}</a>
</div>
<div>
    <a href="{% url 'shopapp:products_list' %}"
    >{% translate 'Back to products list' %}</a>
</div>
{% endblock %}

mysite/shopapp/templates/shopapp/products-list.html
{% extends 'shopapp/base.html' %}

{% load i18n %}

{% block title %}
    {% translate 'Products list' %}
{% endblock %}

{% block body %}
    <h1>{% translate 'Products' %}:</h1>
    {% if products %}
        <div>
            {% blocktranslate count product_count=products|length %}
                There is only one product.
                {% plural %}
                There are {{ product_count }} products.
            {% endblocktranslate %}
        </div>
        <div>
        {% for product in products %}
            <div>
                <p><a href="{% url 'shopapp:product_details' pk=product.pk %}">{% translate 'Name' context 'product name' %}: {{product.name}}</a></p>
                <p>{% translate 'Price' %}: {{product.price}}</p>
                {% translate 'no discount' as no_discount %}
                <p>{% translate 'Discount' %}: {% firstof product.discount no_discount %}</p>
                {% if product.preview %}
                    <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
                {% endif %}
            </div>
        {% endfor %}
        </div>
    {% if 'shopapp.add_product' in perms %}
    <div>
        <a href="{% url 'shopapp:product_create' %}">
            {% translate 'Create a new product' %}
        </a>
    </div>
    {% endif %}
    {% else %}
        {% url 'shopapp:product_create' as create_product_url %}
        {% blocktranslate %}
        <h3>No products yet</h3>
        <a href="{{ create_product_url }}"
            >Create a new one</a>
        {% endblocktranslate %}
    {% endif %}
{% endblock %}

mysite/shopapp/templates/shopapp/products_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools-items %}
{% load admin_urls %}
    <li>
        <a href="{% url 'admin:import_products_csv' %}" class="addlink">
            Import CSV
        </a>
    </li>
    {{ block.super }}
{% endblock %}

mysite/shopapp/templates/shopapp/shop-index.html
{% extends 'shopapp/base.html' %}
{% load cache %}

{% block title %}
    Shop index
{% endblock %}

{% block body %}
    <h1> Список доступных страниц </h1>
    <div>
        <ul>
            {% for link in links %}
                <li><a href={{link.address}}>{{link.title}}</a></li>
            {% empty %}
                No links here
            {% endfor %}
        </ul>
    </div>

    {% cache 100 cherr %}
    <div>
        <strong>
            You have {{ items }} cherr{{ items|pluralize:"y,ies" }}
        </strong>
    </div>
    {% endcache %}

    <div>
        Time running: {{time_running}}
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/user_orders.html
{% extends 'shopapp/base.html' %}
{% load cache %}

{% block title %}
    Orders list
{% endblock %}

{% block body %}
    <h1>The user {{ owner }} made an order(s):</h1>
    {% if object_list %}
    {% cache 300 userinfo owner.pk %}
        <div>
        {% for order in object_list %}
            <div>
                <p><a href="{% url 'shopapp:order_details' pk=order.pk %}">
                    Details # {{ order.pk }}</a></p>
                <p>Order by: {% firstof order.user.first_name order.user.username %}</p>
                <p>Promocode: <code>{{ order.promocode }}</code></p>
                <p>Delivery address: {{ order.delivery_address }}</p>
            </div>
                Products in order:
                <ul>
                    {% for product in order.products.all %}
                        <li>{{ product.name }} for ${{product.price}}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endfor %}
        </div>
    {% endcache %}
    {% else %}
        <h3>The user has no orders yet</h3>
    {% endif %}

    <div>
        <a href="{% url 'shopapp:order_create' %}">
            Create a new order
        </a>
    </div>
{% endblock %}